language: node_js
node_js: "0.11"
before_script:
  - npm install
  - grunt
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bee6497424121cc1673a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  email: false
